package chatpanel;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.net.Socket;

public class ChatPanel extends javax.swing.JFrame {

    String msg;
    String str;
    String s;
    String messageInTopPanel;
    BufferedWriter writer;
    BufferedReader reader;
    Socket sock;

    public ChatPanel() throws IOException {
        messageInTopPanel = "";
        initComponents();
        sock = new Socket("localhost", 30333);
        writer = new BufferedWriter(
                new OutputStreamWriter(sock.getOutputStream()));
        reader = new BufferedReader(
                new InputStreamReader(sock.getInputStream()));
        readMessage();
    }

    void setTextInJTop() throws IOException {
        str = jText.getText();
        s = "" + str;
        // jTop.setText(s);
        writer.write(s);
        writer.newLine();
        writer.flush();
        messageInTopPanel = messageInTopPanel + s + "\n";
        jTop.setText(messageInTopPanel);
        jText.setText("");

    }

    final void readMessage() {
        new Thread(() -> {
            String messageInDownPanel = "";
            while (true) {
                try {
                    msg = reader.readLine();
                } catch (IOException ex) {
                    System.out.println(ex);
                }
                messageInDownPanel += msg + "\n";
                jDown.setText(messageInDownPanel);
            }
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jText = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jDown = new javax.swing.JEditorPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTop = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jText.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton1.setBackground(new java.awt.Color(102, 255, 0));
        jButton1.setText("Send");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                But(evt);
            }
        });

        jDown.setEditable(false);
        jDown.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jDown.setForeground(new java.awt.Color(102, 0, 102));
        jScrollPane1.setViewportView(jDown);

        jTop.setEditable(false);
        jTop.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jTop.setForeground(new java.awt.Color(0, 102, 0));
        jScrollPane2.setViewportView(jTop);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1)
                    .addComponent(jText, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jText, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void But(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_But

        try {

            setTextInJTop();

        } catch (IOException ex) {
            System.out.println(ex);
        }

    }//GEN-LAST:event_But

    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {

                try {
                    new ChatPanel().setVisible(true);
                } catch (IOException ex) {
                }
            }
        });

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JEditorPane jDown;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jText;
    private javax.swing.JEditorPane jTop;
    // End of variables declaration//GEN-END:variables
}
